spring: 
  profiles: 
    active: 
    - dev
---

server:
spring: 
  profiles: dev
  application: 
    name: myblog-user-consumer-6001
  port: 6001
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://129.204.122.20:7001/eureka/,http://121.36.48.89:7002/eureka/
