spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: dev
  application:
    name: myblog-provider-user #对外暴露的微服务的名字
  datasource:
    slave1: #华为云
      password: Ckl333444!
      druid:
        min-idle: 1
        test-on-borrow: true
        stat-view-servlet:
          allow: true
        max-active: 100
        initial-size: 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://121.36.48.89:3306/myblog_user?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
    master: #腾讯云
      password: Ckl333444!
      druid:
        min-idle: 1
        test-on-borrow: true
        stat-view-servlet:
          allow: true
        max-active: 1
        initial-size: 100
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://129.204.122.20:3306/myblog_user?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
  redis:
    redis1:
      database: 0
      password: Ckl333444!
      port: 6379
      host: 121.36.48.89
      timeout: 5000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8

    redis2:
      database: 0
      password: Ckl333444!
      port: 6380
      host: 129.204.122.20
      timeout: 5000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis.cig.xml
  type-aliases-package: com.longer.entities
#eureka配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://129.204.122.20:7001/eureka/,http://121.36.48.89:7002/eureka/
  instance:
    instance-id: myblog-provider-user #修改eureka后面url的名字
    prefer-ip-address: true #设置可以显示ip地址
info:
  app:
    name: myblog-user-provider-8001
  company:
    name: www.longtimenosee.top
  build:
    artifactId: $project.artifactId$
    version: $project.version$


