spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 6001
spring: 
  profiles: dev
  application: 
    name: myblog-user-consumer
#eureka配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://129.204.122.20:7001/eureka/,http://121.36.48.89:7002/eureka/
  instance:
    instance-id: myblog-user-consumer-6001 #修改eureka后面url的名字
    prefer-ip-address: true #设置可以显示ip地址
info:
  app:
    name: myblog-user-consumer-6001
  company:
    name: www.longtimenosee.top
  build:
    artifactId: $project.artifactId$
    version: $project.version$
#加feigin ReadTimtout
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 600000

