spring: 
  profiles: 
    active: 
    - dev
---

server:
  port: 5001
spring: 
  profiles: dev
  application: 
    name: myblog-article-consumer
#eureka配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://129.204.122.20:7001/eureka/,http://121.36.48.89:7002/eureka/
  instance:
    instance-id: myblog-article-consumer-5001 #修改eureka后面url的名字
    prefer-ip-address: true #设置可以显示ip地址
info:
  app:
    name: myblog-article-consumer-5001
  company:
    name: www.longtimenosee.top
  build:
    artifactId: $project.artifactId$
    version: $project.version$

